package com.example.ems_gradle.infra.mbgModel.public;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Employee.emp_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Employee.emp_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Employee.organization_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Employee.position_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Employee.role_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Employee.email
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Employee.password
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Employee.emp_id
     *
     * @return the value of public.Employee.emp_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Employee.emp_id
     *
     * @param empId the value for public.Employee.emp_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Employee.emp_name
     *
     * @return the value of public.Employee.emp_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Employee.emp_name
     *
     * @param empName the value for public.Employee.emp_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Employee.organization_id
     *
     * @return the value of public.Employee.organization_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Employee.organization_id
     *
     * @param organizationId the value for public.Employee.organization_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Employee.position_id
     *
     * @return the value of public.Employee.position_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Employee.position_id
     *
     * @param positionId the value for public.Employee.position_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Employee.role_id
     *
     * @return the value of public.Employee.role_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Employee.role_id
     *
     * @param roleId the value for public.Employee.role_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Employee.email
     *
     * @return the value of public.Employee.email
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Employee.email
     *
     * @param email the value for public.Employee.email
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Employee.password
     *
     * @return the value of public.Employee.password
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Employee.password
     *
     * @param password the value for public.Employee.password
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}