package com.example.ems_gradle.infra.mbgModel.public;

import java.util.Date;

public class Manageequip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ManageEquip.equip_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer equipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ManageEquip.manage_code
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String manageCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ManageEquip.equip_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String equipName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ManageEquip.equip_type_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer equipTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ManageEquip.owner_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ManageEquip.purchase_date
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Date purchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ManageEquip.location
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.ManageEquip.note
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ManageEquip.equip_id
     *
     * @return the value of public.ManageEquip.equip_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ManageEquip.equip_id
     *
     * @param equipId the value for public.ManageEquip.equip_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ManageEquip.manage_code
     *
     * @return the value of public.ManageEquip.manage_code
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getManageCode() {
        return manageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ManageEquip.manage_code
     *
     * @param manageCode the value for public.ManageEquip.manage_code
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setManageCode(String manageCode) {
        this.manageCode = manageCode == null ? null : manageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ManageEquip.equip_name
     *
     * @return the value of public.ManageEquip.equip_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getEquipName() {
        return equipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ManageEquip.equip_name
     *
     * @param equipName the value for public.ManageEquip.equip_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setEquipName(String equipName) {
        this.equipName = equipName == null ? null : equipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ManageEquip.equip_type_id
     *
     * @return the value of public.ManageEquip.equip_type_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getEquipTypeId() {
        return equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ManageEquip.equip_type_id
     *
     * @param equipTypeId the value for public.ManageEquip.equip_type_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setEquipTypeId(Integer equipTypeId) {
        this.equipTypeId = equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ManageEquip.owner_id
     *
     * @return the value of public.ManageEquip.owner_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ManageEquip.owner_id
     *
     * @param ownerId the value for public.ManageEquip.owner_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ManageEquip.purchase_date
     *
     * @return the value of public.ManageEquip.purchase_date
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ManageEquip.purchase_date
     *
     * @param purchaseDate the value for public.ManageEquip.purchase_date
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ManageEquip.location
     *
     * @return the value of public.ManageEquip.location
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ManageEquip.location
     *
     * @param location the value for public.ManageEquip.location
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.ManageEquip.note
     *
     * @return the value of public.ManageEquip.note
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.ManageEquip.note
     *
     * @param note the value for public.ManageEquip.note
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}