package com.example.ems_gradle.infra.mbgModel.public;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Organization.organization_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Organization.group_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Organization.parent_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.Organization.director_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    private String directorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Organization.organization_id
     *
     * @return the value of public.Organization.organization_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Organization.organization_id
     *
     * @param organizationId the value for public.Organization.organization_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setOrganizationId(Integer organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Organization.group_name
     *
     * @return the value of public.Organization.group_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Organization.group_name
     *
     * @param groupName the value for public.Organization.group_name
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Organization.parent_id
     *
     * @return the value of public.Organization.parent_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Organization.parent_id
     *
     * @param parentId the value for public.Organization.parent_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.Organization.director_id
     *
     * @return the value of public.Organization.director_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public String getDirectorId() {
        return directorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.Organization.director_id
     *
     * @param directorId the value for public.Organization.director_id
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    public void setDirectorId(String directorId) {
        this.directorId = directorId == null ? null : directorId.trim();
    }
}