package com.example.ems_gradle.domain.mbgModel.ems;

public class ApprovalFlow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.approval_flow.approval_flow_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    private Integer approvalFlowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.approval_flow.first_approver_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    private Integer firstApproverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.approval_flow.second_approver_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    private Integer secondApproverId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.approval_flow.approval_flow_id
     *
     * @return the value of ems.approval_flow.approval_flow_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    public Integer getApprovalFlowId() {
        return approvalFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.approval_flow.approval_flow_id
     *
     * @param approvalFlowId the value for ems.approval_flow.approval_flow_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    public void setApprovalFlowId(Integer approvalFlowId) {
        this.approvalFlowId = approvalFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.approval_flow.first_approver_id
     *
     * @return the value of ems.approval_flow.first_approver_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    public Integer getFirstApproverId() {
        return firstApproverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.approval_flow.first_approver_id
     *
     * @param firstApproverId the value for ems.approval_flow.first_approver_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    public void setFirstApproverId(Integer firstApproverId) {
        this.firstApproverId = firstApproverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.approval_flow.second_approver_id
     *
     * @return the value of ems.approval_flow.second_approver_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    public Integer getSecondApproverId() {
        return secondApproverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.approval_flow.second_approver_id
     *
     * @param secondApproverId the value for ems.approval_flow.second_approver_id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    public void setSecondApproverId(Integer secondApproverId) {
        this.secondApproverId = secondApproverId;
    }
}