package com.example.ems_gradle.domain.mbgModel.ems;

import java.util.Date;

public class Cancel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.cancel.request_cancel_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer requestCancelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.cancel.cancel_emp_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer cancelEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.cancel.request_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.cancel.request_cancel_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Date requestCancelDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.cancel.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.cancel.request_cancel_id
     *
     * @return the value of ems.cancel.request_cancel_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getRequestCancelId() {
        return requestCancelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.cancel.request_cancel_id
     *
     * @param requestCancelId the value for ems.cancel.request_cancel_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setRequestCancelId(Integer requestCancelId) {
        this.requestCancelId = requestCancelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.cancel.cancel_emp_id
     *
     * @return the value of ems.cancel.cancel_emp_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getCancelEmpId() {
        return cancelEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.cancel.cancel_emp_id
     *
     * @param cancelEmpId the value for ems.cancel.cancel_emp_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setCancelEmpId(Integer cancelEmpId) {
        this.cancelEmpId = cancelEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.cancel.request_id
     *
     * @return the value of ems.cancel.request_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.cancel.request_id
     *
     * @param requestId the value for ems.cancel.request_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.cancel.request_cancel_date
     *
     * @return the value of ems.cancel.request_cancel_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Date getRequestCancelDate() {
        return requestCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.cancel.request_cancel_date
     *
     * @param requestCancelDate the value for ems.cancel.request_cancel_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setRequestCancelDate(Date requestCancelDate) {
        this.requestCancelDate = requestCancelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.cancel.note
     *
     * @return the value of ems.cancel.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.cancel.note
     *
     * @param note the value for ems.cancel.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}