package com.example.ems_gradle.domain.mbgModel.ems;

import java.util.Date;

public class Edit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.edit_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer editId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.edit_emp_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer editEmpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.equip_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer equipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.equip_type_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer equipTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.owner_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.edit_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Date editDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.purchase_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Date purchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.equip_manage_code
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String equipManageCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.equip_name
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String equipName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.location
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.edit.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.edit_id
     *
     * @return the value of ems.edit.edit_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getEditId() {
        return editId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.edit_id
     *
     * @param editId the value for ems.edit.edit_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEditId(Integer editId) {
        this.editId = editId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.edit_emp_id
     *
     * @return the value of ems.edit.edit_emp_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getEditEmpId() {
        return editEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.edit_emp_id
     *
     * @param editEmpId the value for ems.edit.edit_emp_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEditEmpId(Integer editEmpId) {
        this.editEmpId = editEmpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.equip_id
     *
     * @return the value of ems.edit.equip_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.equip_id
     *
     * @param equipId the value for ems.edit.equip_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.equip_type_id
     *
     * @return the value of ems.edit.equip_type_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getEquipTypeId() {
        return equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.equip_type_id
     *
     * @param equipTypeId the value for ems.edit.equip_type_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEquipTypeId(Integer equipTypeId) {
        this.equipTypeId = equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.owner_id
     *
     * @return the value of ems.edit.owner_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.owner_id
     *
     * @param ownerId the value for ems.edit.owner_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.edit_date
     *
     * @return the value of ems.edit.edit_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Date getEditDate() {
        return editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.edit_date
     *
     * @param editDate the value for ems.edit.edit_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEditDate(Date editDate) {
        this.editDate = editDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.purchase_date
     *
     * @return the value of ems.edit.purchase_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.purchase_date
     *
     * @param purchaseDate the value for ems.edit.purchase_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.equip_manage_code
     *
     * @return the value of ems.edit.equip_manage_code
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getEquipManageCode() {
        return equipManageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.equip_manage_code
     *
     * @param equipManageCode the value for ems.edit.equip_manage_code
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEquipManageCode(String equipManageCode) {
        this.equipManageCode = equipManageCode == null ? null : equipManageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.equip_name
     *
     * @return the value of ems.edit.equip_name
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getEquipName() {
        return equipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.equip_name
     *
     * @param equipName the value for ems.edit.equip_name
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEquipName(String equipName) {
        this.equipName = equipName == null ? null : equipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.location
     *
     * @return the value of ems.edit.location
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.location
     *
     * @param location the value for ems.edit.location
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.edit.note
     *
     * @return the value of ems.edit.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.edit.note
     *
     * @param note the value for ems.edit.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}