package com.example.ems_gradle.domain.mbgModel.ems;

import java.util.Date;

public class Equip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip.equip_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer equipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip.equip_type_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer equipTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip.owner_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip.purchase_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Date purchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip.equip_manage_code
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String equipManageCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip.equip_name
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String equipName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip.location
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip.equip_id
     *
     * @return the value of ems.equip.equip_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip.equip_id
     *
     * @param equipId the value for ems.equip.equip_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip.equip_type_id
     *
     * @return the value of ems.equip.equip_type_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getEquipTypeId() {
        return equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip.equip_type_id
     *
     * @param equipTypeId the value for ems.equip.equip_type_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEquipTypeId(Integer equipTypeId) {
        this.equipTypeId = equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip.owner_id
     *
     * @return the value of ems.equip.owner_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip.owner_id
     *
     * @param ownerId the value for ems.equip.owner_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip.purchase_date
     *
     * @return the value of ems.equip.purchase_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip.purchase_date
     *
     * @param purchaseDate the value for ems.equip.purchase_date
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip.equip_manage_code
     *
     * @return the value of ems.equip.equip_manage_code
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getEquipManageCode() {
        return equipManageCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip.equip_manage_code
     *
     * @param equipManageCode the value for ems.equip.equip_manage_code
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEquipManageCode(String equipManageCode) {
        this.equipManageCode = equipManageCode == null ? null : equipManageCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip.equip_name
     *
     * @return the value of ems.equip.equip_name
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getEquipName() {
        return equipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip.equip_name
     *
     * @param equipName the value for ems.equip.equip_name
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setEquipName(String equipName) {
        this.equipName = equipName == null ? null : equipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip.location
     *
     * @return the value of ems.equip.location
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip.location
     *
     * @param location the value for ems.equip.location
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip.note
     *
     * @return the value of ems.equip.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip.note
     *
     * @param note the value for ems.equip.note
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}