package com.example.ems_gradle.domain.mbgModel.ems;

public class Request {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.request.request_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private Integer requestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.request.request_status
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    private String requestStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.request.request_id
     *
     * @return the value of ems.request.request_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.request.request_id
     *
     * @param requestId the value for ems.request.request_id
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setRequestId(Integer requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.request.request_status
     *
     * @return the value of ems.request.request_status
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getRequestStatus() {
        return requestStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.request.request_status
     *
     * @param requestStatus the value for ems.request.request_status
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setRequestStatus(String requestStatus) {
        this.requestStatus = requestStatus == null ? null : requestStatus.trim();
    }
}