package com.example.ems_gradle.domain.mbgModel.ems;

public class Sample {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.sample.id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.sample.id
     *
     * @return the value of ems.sample.id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.sample.id
     *
     * @param id the value for ems.sample.id
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }
}