package com.example.ems_gradle.domain.mbgModel.ems;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SecondApproveExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public SecondApproveExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRequestSecondApproveIdIsNull() {
            addCriterion("request_second_approve_id is null");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdIsNotNull() {
            addCriterion("request_second_approve_id is not null");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdEqualTo(Integer value) {
            addCriterion("request_second_approve_id =", value, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdNotEqualTo(Integer value) {
            addCriterion("request_second_approve_id <>", value, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdGreaterThan(Integer value) {
            addCriterion("request_second_approve_id >", value, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("request_second_approve_id >=", value, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdLessThan(Integer value) {
            addCriterion("request_second_approve_id <", value, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdLessThanOrEqualTo(Integer value) {
            addCriterion("request_second_approve_id <=", value, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdIn(List<Integer> values) {
            addCriterion("request_second_approve_id in", values, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdNotIn(List<Integer> values) {
            addCriterion("request_second_approve_id not in", values, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdBetween(Integer value1, Integer value2) {
            addCriterion("request_second_approve_id between", value1, value2, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveIdNotBetween(Integer value1, Integer value2) {
            addCriterion("request_second_approve_id not between", value1, value2, "requestSecondApproveId");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNull() {
            addCriterion("request_id is null");
            return (Criteria) this;
        }

        public Criteria andRequestIdIsNotNull() {
            addCriterion("request_id is not null");
            return (Criteria) this;
        }

        public Criteria andRequestIdEqualTo(Integer value) {
            addCriterion("request_id =", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotEqualTo(Integer value) {
            addCriterion("request_id <>", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThan(Integer value) {
            addCriterion("request_id >", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("request_id >=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThan(Integer value) {
            addCriterion("request_id <", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdLessThanOrEqualTo(Integer value) {
            addCriterion("request_id <=", value, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdIn(List<Integer> values) {
            addCriterion("request_id in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotIn(List<Integer> values) {
            addCriterion("request_id not in", values, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdBetween(Integer value1, Integer value2) {
            addCriterion("request_id between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andRequestIdNotBetween(Integer value1, Integer value2) {
            addCriterion("request_id not between", value1, value2, "requestId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdIsNull() {
            addCriterion("second_approve_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdIsNotNull() {
            addCriterion("second_approve_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdEqualTo(Integer value) {
            addCriterion("second_approve_user_id =", value, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdNotEqualTo(Integer value) {
            addCriterion("second_approve_user_id <>", value, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdGreaterThan(Integer value) {
            addCriterion("second_approve_user_id >", value, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("second_approve_user_id >=", value, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdLessThan(Integer value) {
            addCriterion("second_approve_user_id <", value, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("second_approve_user_id <=", value, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdIn(List<Integer> values) {
            addCriterion("second_approve_user_id in", values, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdNotIn(List<Integer> values) {
            addCriterion("second_approve_user_id not in", values, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdBetween(Integer value1, Integer value2) {
            addCriterion("second_approve_user_id between", value1, value2, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andSecondApproveUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("second_approve_user_id not between", value1, value2, "secondApproveUserId");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateIsNull() {
            addCriterion("request_second_approve_date is null");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateIsNotNull() {
            addCriterion("request_second_approve_date is not null");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateEqualTo(Date value) {
            addCriterion("request_second_approve_date =", value, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateNotEqualTo(Date value) {
            addCriterion("request_second_approve_date <>", value, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateGreaterThan(Date value) {
            addCriterion("request_second_approve_date >", value, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateGreaterThanOrEqualTo(Date value) {
            addCriterion("request_second_approve_date >=", value, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateLessThan(Date value) {
            addCriterion("request_second_approve_date <", value, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateLessThanOrEqualTo(Date value) {
            addCriterion("request_second_approve_date <=", value, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateIn(List<Date> values) {
            addCriterion("request_second_approve_date in", values, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateNotIn(List<Date> values) {
            addCriterion("request_second_approve_date not in", values, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateBetween(Date value1, Date value2) {
            addCriterion("request_second_approve_date between", value1, value2, "requestSecondApproveDate");
            return (Criteria) this;
        }

        public Criteria andRequestSecondApproveDateNotBetween(Date value1, Date value2) {
            addCriterion("request_second_approve_date not between", value1, value2, "requestSecondApproveDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems.second_approve
     *
     * @mbg.generated do_not_delete_during_merge Sat Sep 02 09:13:33 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems.second_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}