package com.example.ems_gradle.infra.mbgMapper.public;

import com.example.ems_gradle.infra.mbgModel.public.Approvalflow;
import com.example.ems_gradle.infra.mbgModel.public.ApprovalflowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApprovalflowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    long countByExample(ApprovalflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int deleteByExample(ApprovalflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int deleteByPrimaryKey(Integer approvalFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int insert(Approvalflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int insertSelective(Approvalflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    List<Approvalflow> selectByExample(ApprovalflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    Approvalflow selectByPrimaryKey(Integer approvalFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByExampleSelective(@Param("row") Approvalflow row, @Param("example") ApprovalflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByExample(@Param("row") Approvalflow row, @Param("example") ApprovalflowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByPrimaryKeySelective(Approvalflow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ApprovalFlow
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByPrimaryKey(Approvalflow row);
}