package com.example.ems_gradle.infra.mbgMapper.public;

import com.example.ems_gradle.infra.mbgModel.public.Equiptype;
import com.example.ems_gradle.infra.mbgModel.public.EquiptypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquiptypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    long countByExample(EquiptypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int deleteByExample(EquiptypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int deleteByPrimaryKey(Integer equipTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int insert(Equiptype row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int insertSelective(Equiptype row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    List<Equiptype> selectByExample(EquiptypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    Equiptype selectByPrimaryKey(Integer equipTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByExampleSelective(@Param("row") Equiptype row, @Param("example") EquiptypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByExample(@Param("row") Equiptype row, @Param("example") EquiptypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByPrimaryKeySelective(Equiptype row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.EquipType
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByPrimaryKey(Equiptype row);
}