package com.example.ems_gradle.infra.mbgMapper.public;

import com.example.ems_gradle.infra.mbgModel.public.Organization;
import com.example.ems_gradle.infra.mbgModel.public.OrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    long countByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int deleteByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int deleteByPrimaryKey(Integer organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int insert(Organization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int insertSelective(Organization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    List<Organization> selectByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    Organization selectByPrimaryKey(Integer organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByExampleSelective(@Param("row") Organization row, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByExample(@Param("row") Organization row, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByPrimaryKeySelective(Organization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.Organization
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByPrimaryKey(Organization row);
}