package com.example.ems_gradle.infra.mbgMapper.public;

import com.example.ems_gradle.infra.mbgModel.public.Progressstatus;
import com.example.ems_gradle.infra.mbgModel.public.ProgressstatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProgressstatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    long countByExample(ProgressstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int deleteByExample(ProgressstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int deleteByPrimaryKey(Integer progressStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int insert(Progressstatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int insertSelective(Progressstatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    List<Progressstatus> selectByExample(ProgressstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    Progressstatus selectByPrimaryKey(Integer progressStatusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByExampleSelective(@Param("row") Progressstatus row, @Param("example") ProgressstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByExample(@Param("row") Progressstatus row, @Param("example") ProgressstatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByPrimaryKeySelective(Progressstatus row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ProgressStatus
     *
     * @mbg.generated Mon Aug 07 22:08:05 JST 2023
     */
    int updateByPrimaryKey(Progressstatus row);
}