package com.example.ems_gradle.infra.mbgModel.ems;

import java.util.Date;

public class Confirm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.confirm.confirm_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer confirmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.confirm.equip_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer equipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.confirm.execute_date
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Date executeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.confirm.executer_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer executerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.confirm.check_status_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer checkStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.confirm.note
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.confirm.confirm_id
     *
     * @return the value of ems.confirm.confirm_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getConfirmId() {
        return confirmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.confirm.confirm_id
     *
     * @param confirmId the value for ems.confirm.confirm_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setConfirmId(Integer confirmId) {
        this.confirmId = confirmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.confirm.equip_id
     *
     * @return the value of ems.confirm.equip_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getEquipId() {
        return equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.confirm.equip_id
     *
     * @param equipId the value for ems.confirm.equip_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setEquipId(Integer equipId) {
        this.equipId = equipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.confirm.execute_date
     *
     * @return the value of ems.confirm.execute_date
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Date getExecuteDate() {
        return executeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.confirm.execute_date
     *
     * @param executeDate the value for ems.confirm.execute_date
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setExecuteDate(Date executeDate) {
        this.executeDate = executeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.confirm.executer_id
     *
     * @return the value of ems.confirm.executer_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getExecuterId() {
        return executerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.confirm.executer_id
     *
     * @param executerId the value for ems.confirm.executer_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setExecuterId(Integer executerId) {
        this.executerId = executerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.confirm.check_status_id
     *
     * @return the value of ems.confirm.check_status_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getCheckStatusId() {
        return checkStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.confirm.check_status_id
     *
     * @param checkStatusId the value for ems.confirm.check_status_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setCheckStatusId(Integer checkStatusId) {
        this.checkStatusId = checkStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.confirm.note
     *
     * @return the value of ems.confirm.note
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.confirm.note
     *
     * @param note the value for ems.confirm.note
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}