package com.example.ems_gradle.infra.mbgModel.ems;

public class EquipType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip_type.equip_type_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer equipTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.equip_type.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private String equipType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip_type.equip_type_id
     *
     * @return the value of ems.equip_type.equip_type_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getEquipTypeId() {
        return equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip_type.equip_type_id
     *
     * @param equipTypeId the value for ems.equip_type.equip_type_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setEquipTypeId(Integer equipTypeId) {
        this.equipTypeId = equipTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.equip_type.equip_type
     *
     * @return the value of ems.equip_type.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public String getEquipType() {
        return equipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.equip_type.equip_type
     *
     * @param equipType the value for ems.equip_type.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setEquipType(String equipType) {
        this.equipType = equipType == null ? null : equipType.trim();
    }
}