package com.example.ems_gradle.infra.mbgModel.ems;

import java.util.Date;

public class Operationtomanage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.OperationToManage.operation_manage_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    private Integer operationManageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.OperationToManage.discriminate_table_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    private Integer discriminateTableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.OperationToManage.operation_date
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    private Date operationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.OperationToManage.operator_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.OperationToManage.operation_type_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    private Integer operationTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.OperationToManage.message
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.OperationToManage.operation_manage_id
     *
     * @return the value of ems.OperationToManage.operation_manage_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public Integer getOperationManageId() {
        return operationManageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.OperationToManage.operation_manage_id
     *
     * @param operationManageId the value for ems.OperationToManage.operation_manage_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public void setOperationManageId(Integer operationManageId) {
        this.operationManageId = operationManageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.OperationToManage.discriminate_table_id
     *
     * @return the value of ems.OperationToManage.discriminate_table_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public Integer getDiscriminateTableId() {
        return discriminateTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.OperationToManage.discriminate_table_id
     *
     * @param discriminateTableId the value for ems.OperationToManage.discriminate_table_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public void setDiscriminateTableId(Integer discriminateTableId) {
        this.discriminateTableId = discriminateTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.OperationToManage.operation_date
     *
     * @return the value of ems.OperationToManage.operation_date
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.OperationToManage.operation_date
     *
     * @param operationDate the value for ems.OperationToManage.operation_date
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.OperationToManage.operator_id
     *
     * @return the value of ems.OperationToManage.operator_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.OperationToManage.operator_id
     *
     * @param operatorId the value for ems.OperationToManage.operator_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.OperationToManage.operation_type_id
     *
     * @return the value of ems.OperationToManage.operation_type_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public Integer getOperationTypeId() {
        return operationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.OperationToManage.operation_type_id
     *
     * @param operationTypeId the value for ems.OperationToManage.operation_type_id
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public void setOperationTypeId(Integer operationTypeId) {
        this.operationTypeId = operationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.OperationToManage.message
     *
     * @return the value of ems.OperationToManage.message
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.OperationToManage.message
     *
     * @param message the value for ems.OperationToManage.message
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}