package com.example.ems_gradle.infra.mbgModel.ems;

import java.util.Date;

public class OperationToRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.operation_to_request.operation_request_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer operationRequestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.operation_to_request.discriminate_table_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer discriminateTableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.operation_to_request.operation_date
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Date operationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.operation_to_request.operator_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.operation_to_request.operation_type_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private Integer operationTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems.operation_to_request.message
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.operation_to_request.operation_request_id
     *
     * @return the value of ems.operation_to_request.operation_request_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getOperationRequestId() {
        return operationRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.operation_to_request.operation_request_id
     *
     * @param operationRequestId the value for ems.operation_to_request.operation_request_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setOperationRequestId(Integer operationRequestId) {
        this.operationRequestId = operationRequestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.operation_to_request.discriminate_table_id
     *
     * @return the value of ems.operation_to_request.discriminate_table_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getDiscriminateTableId() {
        return discriminateTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.operation_to_request.discriminate_table_id
     *
     * @param discriminateTableId the value for ems.operation_to_request.discriminate_table_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setDiscriminateTableId(Integer discriminateTableId) {
        this.discriminateTableId = discriminateTableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.operation_to_request.operation_date
     *
     * @return the value of ems.operation_to_request.operation_date
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Date getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.operation_to_request.operation_date
     *
     * @param operationDate the value for ems.operation_to_request.operation_date
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setOperationDate(Date operationDate) {
        this.operationDate = operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.operation_to_request.operator_id
     *
     * @return the value of ems.operation_to_request.operator_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.operation_to_request.operator_id
     *
     * @param operatorId the value for ems.operation_to_request.operator_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.operation_to_request.operation_type_id
     *
     * @return the value of ems.operation_to_request.operation_type_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public Integer getOperationTypeId() {
        return operationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.operation_to_request.operation_type_id
     *
     * @param operationTypeId the value for ems.operation_to_request.operation_type_id
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setOperationTypeId(Integer operationTypeId) {
        this.operationTypeId = operationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems.operation_to_request.message
     *
     * @return the value of ems.operation_to_request.message
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems.operation_to_request.message
     *
     * @param message the value for ems.operation_to_request.message
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}