package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.ApprovalFlow;
import com.example.ems_gradle.infra.mbgModel.ems.ApprovalFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApprovalFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    long countByExample(ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int deleteByExample(ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int deleteByPrimaryKey(Integer approvalFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int insert(ApprovalFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int insertSelective(ApprovalFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    List<ApprovalFlow> selectByExample(ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    ApprovalFlow selectByPrimaryKey(Integer approvalFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByExampleSelective(@Param("row") ApprovalFlow row, @Param("example") ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByExample(@Param("row") ApprovalFlow row, @Param("example") ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByPrimaryKeySelective(ApprovalFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.approval_flow
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByPrimaryKey(ApprovalFlow row);
}