package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.Cancel;
import com.example.ems_gradle.domain.mbgModel.ems.CancelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CancelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    long countByExample(CancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int deleteByExample(CancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int deleteByPrimaryKey(Integer requestActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int insert(Cancel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int insertSelective(Cancel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    List<Cancel> selectByExample(CancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    Cancel selectByPrimaryKey(Integer requestActivityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByExampleSelective(@Param("row") Cancel row, @Param("example") CancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByExample(@Param("row") Cancel row, @Param("example") CancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByPrimaryKeySelective(Cancel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.cancel
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByPrimaryKey(Cancel row);
}