package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.Confirm;
import com.example.ems_gradle.infra.mbgModel.ems.ConfirmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfirmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    long countByExample(ConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int deleteByExample(ConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int deleteByPrimaryKey(Integer confirmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int insert(Confirm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int insertSelective(Confirm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    List<Confirm> selectByExample(ConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    Confirm selectByPrimaryKey(Integer confirmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByExampleSelective(@Param("row") Confirm row, @Param("example") ConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByExample(@Param("row") Confirm row, @Param("example") ConfirmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByPrimaryKeySelective(Confirm row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.Confirm
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByPrimaryKey(Confirm row);
}