package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.DivisionUser;
import com.example.ems_gradle.domain.mbgModel.ems.DivisionUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DivisionUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    long countByExample(DivisionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int deleteByExample(DivisionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int insert(DivisionUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int insertSelective(DivisionUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    List<DivisionUser> selectByExample(DivisionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    DivisionUser selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByExampleSelective(@Param("row") DivisionUser row, @Param("example") DivisionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByExample(@Param("row") DivisionUser row, @Param("example") DivisionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByPrimaryKeySelective(DivisionUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.division_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByPrimaryKey(DivisionUser row);
}