package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.Edit;
import com.example.ems_gradle.domain.mbgModel.ems.EditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    long countByExample(EditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int deleteByExample(EditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int deleteByPrimaryKey(Integer editId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int insert(Edit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int insertSelective(Edit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    List<Edit> selectByExample(EditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    Edit selectByPrimaryKey(Integer editId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByExampleSelective(@Param("row") Edit row, @Param("example") EditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByExample(@Param("row") Edit row, @Param("example") EditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByPrimaryKeySelective(Edit row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.edit
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByPrimaryKey(Edit row);
}