package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.EquipType;
import com.example.ems_gradle.infra.mbgModel.ems.EquipTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquipTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    long countByExample(EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int deleteByExample(EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int deleteByPrimaryKey(Integer equipTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int insert(EquipType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int insertSelective(EquipType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    List<EquipType> selectByExample(EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    EquipType selectByPrimaryKey(Integer equipTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByExampleSelective(@Param("row") EquipType row, @Param("example") EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByExample(@Param("row") EquipType row, @Param("example") EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByPrimaryKeySelective(EquipType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip_type
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByPrimaryKey(EquipType row);
}