package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.Equip;
import com.example.ems_gradle.domain.mbgModel.ems.EquipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EquipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    long countByExample(EquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int deleteByExample(EquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int deleteByPrimaryKey(Integer equipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int insert(Equip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int insertSelective(Equip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    List<Equip> selectByExample(EquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    Equip selectByPrimaryKey(Integer equipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByExampleSelective(@Param("row") Equip row, @Param("example") EquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByExample(@Param("row") Equip row, @Param("example") EquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByPrimaryKeySelective(Equip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.equip
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByPrimaryKey(Equip row);
}