package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.FirstApprove;
import com.example.ems_gradle.domain.mbgModel.ems.FirstApproveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FirstApproveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    long countByExample(FirstApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int deleteByExample(FirstApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int deleteByPrimaryKey(Integer requestFirstApproveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int insert(FirstApprove row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int insertSelective(FirstApprove row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    List<FirstApprove> selectByExample(FirstApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    FirstApprove selectByPrimaryKey(Integer requestFirstApproveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByExampleSelective(@Param("row") FirstApprove row, @Param("example") FirstApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByExample(@Param("row") FirstApprove row, @Param("example") FirstApproveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByPrimaryKeySelective(FirstApprove row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.first_approve
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByPrimaryKey(FirstApprove row);
}