package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.Manageequip;
import com.example.ems_gradle.infra.mbgModel.ems.ManageequipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ManageequipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    long countByExample(ManageequipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int deleteByExample(ManageequipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int deleteByPrimaryKey(Integer equipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int insert(Manageequip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int insertSelective(Manageequip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    List<Manageequip> selectByExample(ManageequipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    Manageequip selectByPrimaryKey(Integer equipId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int updateByExampleSelective(@Param("row") Manageequip row, @Param("example") ManageequipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int updateByExample(@Param("row") Manageequip row, @Param("example") ManageequipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int updateByPrimaryKeySelective(Manageequip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.ManageEquip
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int updateByPrimaryKey(Manageequip row);
}