package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.OperationToRequest;
import com.example.ems_gradle.domain.mbgModel.ems.OperationToRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationToRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    long countByExample(OperationToRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int deleteByExample(OperationToRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int deleteByPrimaryKey(Integer operationRequestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int insert(OperationToRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int insertSelective(OperationToRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    List<OperationToRequest> selectByExample(OperationToRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    OperationToRequest selectByPrimaryKey(Integer operationRequestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByExampleSelective(@Param("row") OperationToRequest row, @Param("example") OperationToRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByExample(@Param("row") OperationToRequest row, @Param("example") OperationToRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByPrimaryKeySelective(OperationToRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_request
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByPrimaryKey(OperationToRequest row);
}