package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.Operationtomanage;
import com.example.ems_gradle.infra.mbgModel.ems.OperationtomanageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationtomanageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    long countByExample(OperationtomanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int deleteByExample(OperationtomanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int deleteByPrimaryKey(Integer operationManageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int insert(Operationtomanage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int insertSelective(Operationtomanage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    List<Operationtomanage> selectByExample(OperationtomanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    Operationtomanage selectByPrimaryKey(Integer operationManageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByExampleSelective(@Param("row") Operationtomanage row, @Param("example") OperationtomanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByExample(@Param("row") Operationtomanage row, @Param("example") OperationtomanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByPrimaryKeySelective(Operationtomanage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToManage
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByPrimaryKey(Operationtomanage row);
}