package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.Operationtorequest;
import com.example.ems_gradle.infra.mbgModel.ems.OperationtorequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationtorequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    long countByExample(OperationtorequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int deleteByExample(OperationtorequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int deleteByPrimaryKey(Integer operationRequestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int insert(Operationtorequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int insertSelective(Operationtorequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    List<Operationtorequest> selectByExample(OperationtorequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    Operationtorequest selectByPrimaryKey(Integer operationRequestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByExampleSelective(@Param("row") Operationtorequest row, @Param("example") OperationtorequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByExample(@Param("row") Operationtorequest row, @Param("example") OperationtorequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByPrimaryKeySelective(Operationtorequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationToRequest
     *
     * @mbg.generated Wed Aug 09 22:08:33 JST 2023
     */
    int updateByPrimaryKey(Operationtorequest row);
}