package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.Operationhistory;
import com.example.ems_gradle.infra.mbgModel.ems.OperationhistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationhistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    long countByExample(OperationhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int deleteByExample(OperationhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int deleteByPrimaryKey(Integer operationHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int insert(Operationhistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int insertSelective(Operationhistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    List<Operationhistory> selectByExample(OperationhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    Operationhistory selectByPrimaryKey(Integer operationHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int updateByExampleSelective(@Param("row") Operationhistory row, @Param("example") OperationhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int updateByExample(@Param("row") Operationhistory row, @Param("example") OperationhistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int updateByPrimaryKeySelective(Operationhistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.OperationHistory
     *
     * @mbg.generated Mon Aug 07 22:26:29 JST 2023
     */
    int updateByPrimaryKey(Operationhistory row);
}