package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.OperationToManage;
import com.example.ems_gradle.infra.mbgModel.ems.OperationToManageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationToManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    long countByExample(OperationToManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int deleteByExample(OperationToManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int deleteByPrimaryKey(Integer operationManageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int insert(OperationToManage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int insertSelective(OperationToManage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    List<OperationToManage> selectByExample(OperationToManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    OperationToManage selectByPrimaryKey(Integer operationManageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByExampleSelective(@Param("row") OperationToManage row, @Param("example") OperationToManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByExample(@Param("row") OperationToManage row, @Param("example") OperationToManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByPrimaryKeySelective(OperationToManage row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.operation_to_manage
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByPrimaryKey(OperationToManage row);
}