package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.infra.mbgModel.ems.Organization;
import com.example.ems_gradle.infra.mbgModel.ems.OrganizationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    long countByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int deleteByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int deleteByPrimaryKey(Integer organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int insert(Organization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int insertSelective(Organization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    List<Organization> selectByExample(OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    Organization selectByPrimaryKey(Integer organizationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByExampleSelective(@Param("row") Organization row, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByExample(@Param("row") Organization row, @Param("example") OrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByPrimaryKeySelective(Organization row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.organization
     *
     * @mbg.generated Sat Aug 12 10:45:47 JST 2023
     */
    int updateByPrimaryKey(Organization row);
}