package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.Receive;
import com.example.ems_gradle.domain.mbgModel.ems.ReceiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    long countByExample(ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int deleteByExample(ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int deleteByPrimaryKey(Integer requestReceiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int insert(Receive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int insertSelective(Receive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    List<Receive> selectByExample(ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    Receive selectByPrimaryKey(Integer requestReceiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByExampleSelective(@Param("row") Receive row, @Param("example") ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByExample(@Param("row") Receive row, @Param("example") ReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByPrimaryKeySelective(Receive row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.receive
     *
     * @mbg.generated Sat Sep 02 09:13:33 JST 2023
     */
    int updateByPrimaryKey(Receive row);
}