package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.RequestEquip;
import com.example.ems_gradle.domain.mbgModel.ems.RequestEquipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RequestEquipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    long countByExample(RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int deleteByExample(RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int deleteByPrimaryKey(Integer requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int insert(RequestEquip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int insertSelective(RequestEquip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    List<RequestEquip> selectByExample(RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    RequestEquip selectByPrimaryKey(Integer requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByExampleSelective(@Param("row") RequestEquip row, @Param("example") RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByExample(@Param("row") RequestEquip row, @Param("example") RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByPrimaryKeySelective(RequestEquip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.request_equip
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByPrimaryKey(RequestEquip row);
}