package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.Sample;
import com.example.ems_gradle.domain.mbgModel.ems.SampleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SampleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.sample
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    long countByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.sample
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int deleteByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.sample
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.sample
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int insert(Sample row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.sample
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int insertSelective(Sample row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.sample
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    List<Sample> selectByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.sample
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByExampleSelective(@Param("row") Sample row, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.sample
     *
     * @mbg.generated Wed Aug 16 22:37:18 JST 2023
     */
    int updateByExample(@Param("row") Sample row, @Param("example") SampleExample example);
}