package com.example.ems_gradle.infra.mbgMapper.ems;

import com.example.ems_gradle.domain.mbgModel.ems.SectionUser;
import com.example.ems_gradle.domain.mbgModel.ems.SectionUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SectionUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    long countByExample(SectionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int deleteByExample(SectionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int insert(SectionUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int insertSelective(SectionUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    List<SectionUser> selectByExample(SectionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    SectionUser selectByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByExampleSelective(@Param("row") SectionUser row, @Param("example") SectionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByExample(@Param("row") SectionUser row, @Param("example") SectionUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByPrimaryKeySelective(SectionUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems.section_user
     *
     * @mbg.generated Wed Aug 30 22:13:36 JST 2023
     */
    int updateByPrimaryKey(SectionUser row);
}